#ifndef _ENGINE_CONFIG_H_
#define _ENGINE_CONFIG_H_

#define DSP_WID 320
#define DSP_HEI 240
#define DSP_RES RESOLUTION_320x240
#define DSP_DEP DEPTH_16_BPP
#define DSP_BUF_CNT 3
#define DSP_GAM GAMMA_NONE
#define DSP_FIL FILTERS_RESAMPLE

#define BASE_FONT_ID 1

#define TICKRATE 60
#define DELTATIME (1.0f / TICKRATE)
#define DELTATICKS (DELTATIME * TICKS_PER_SECOND)

#define STICK_DEADZONE 40

#endif /* _ENGINE_CONFIG_H_ */
